function [ pointOut ] = Inverse( x,y,z,a,b,c,pointIn )
%???????????x,y,z,a,b,c?????????pointIn??????????pointOut
%????????????-??-??-??

%????
T = [1 0 0 x;...
     0 1 0 y;...
     0 0 1 z;...
     0 0 0 1];
 %?? YAW
 Ra = [1,   0,        0,        0;...
       0,   cosd(a),  -sind(a),  0;...
       0,   sind(a), cosd(a),  0;...
       0    0         0         1];
 %?? ROLL
 Rb = [cosd(b),  0,  sind(b), 0;...
       0        1   0       0;...
       -sind(b), 0,  cosd(b), 0;...
       0        0   0       1];
%??
 Rc = [cosd(c),   -sind(c),  0, 0;...
       sind(c),  cosd(c),  0, 0;...
       0,         0,        1, 0;...
       0,         0,        0, 1];
 pointOut = [ T * Rc * Rb * Ra * pointIn']';
end

